// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xslojsghekmsqozirlse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzbG9qc2doZWttc3FvemlybHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTIwODAsImV4cCI6MjA3MTM2ODA4MH0.6nXa2RC1ASMo2HDpauf0bWSd0PTaNrsMS1n3RuF8_po";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Tạo single instance để tránh multiple client warnings
let _supabaseClient: ReturnType<typeof createClient<Database>> | null = null;

export const supabase = (() => {
  if (!_supabaseClient) {
    _supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: false, // Ngăn auto-detect session từ URL
        flowType: 'pkce' // Sử dụng PKCE flow để tăng security và stability
      },
      realtime: {
        params: {
          eventsPerSecond: 10 // Giảm tần suất events để tránh quá tải
        }
      }
    });
  }
  return _supabaseClient;
})();